### ISSUE TITLE
Create wireframe for launch cards

### ISSUE THREAD

**Issue by dominik-ilja** [Dominik-Ilja/solar-conveyance#6]

**Comment by danielchen2003** [comment]
<img width="622" alt="2022-08-07 下午11 27 05" src="https://user-images.githubusercontent.com/104922779/183332721-a5d8e09a-bc5c-4d93-81b4-84fbd9ae6b85.png">

**Comment by dominik-ilja** [comment]
> <img alt="2022-08-07 下午11 27 05" width="622" src="https://user-images.githubusercontent.com/104922779/183332721-a5d8e09a-bc5c-4d93-81b4-84fbd9ae6b85.png">

I'd like you to make a commit for this wire frame.
